spring:
  cloud:
    aws:
      credentials:
        profile-name: dev
      region:
        static: ap-northeast-2
      parameter-store:
        enabled: false
      s3:
        bucket: ${AWS_S3_BUCKET_NAME}
  datasource:
    url: jdbc:mysql://localhost:3306/${db_name}
    username: ${db_username}
    password: ${db_password}
    driver-class-name: com.mysql.cj.jdbc.Driver

  data:
    redis:
      host: localhost   # ğŸ”¥ Redis Docker ì»¨í…Œì´ë„ˆ ë¡œì»¬ ì‹¤í–‰ ì¤‘
      port: 6379

  cache:
    type: redis
    redis:
      time-to-live: 3600s        # 1ì‹œê°„
      cache-null-values: false   # null ê²°ê³¼ ìºì‹± ë°©ì§€

  mail:
    username: ${EMAIL}
    password: ${PASSWORD}
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    transport:
      protocol: smtp
    smtp:
      auth: true
      starttls:
        enable: true
      connectiontimeout: 5s  # ì—°ê²° íƒ€ì„ì•„ì›ƒ (5ì´ˆ)
      timeout: 5s           # ì½ê¸° íƒ€ì„ì•„ì›ƒ (5ì´ˆ)
      writetimeout: 5s      # ì“°ê¸° íƒ€ì„ì•„ì›ƒ (5ì´ˆ)

  #RabbitMQ
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    listener:
      simple:
        acknowledge-mode: manual # ACK ìˆ˜ë™ ì„¤ì •

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

rabbitmq:
  dlq:
    confirm-timeout-ms: 5000

jwt:
  secret: ${JWT_SECRET}

auth:
  base-url: "http://localhost:8080"
  server:
    ssl:
      enabled: false  # ë¡œì»¬ ê°œë°œí™˜ê²½ì€ HTTP ì‚¬ìš©
  security:
    cookie:
      secure: false  # HTTP í™˜ê²½ì—ì„œëŠ” Secure ì†ì„± ë¶ˆí•„ìš”

logging:
  level:
    org.hibernate.SQL: debug

springdoc:
  api-docs.enabled: true
  swagger-ui:
    enabled: true
    display-request-duration: true
    tryItOutEnabled: true
